"""empty message

Revision ID: 16455f3f966b
Revises: b421aae5cf2a
Create Date: 2021-05-29 17:06:16.093915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16455f3f966b'
down_revision = 'b421aae5cf2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('attendees', sa.PickleType(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
