"""empty message

Revision ID: 90d3d98685ff
Revises: 16455f3f966b
Create Date: 2021-06-09 23:31:37.164826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d3d98685ff'
down_revision = '16455f3f966b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'room_id')
    # ### end Alembic commands ###
